import React from "react";
import { render, screen } from "@testing-library/react";
import Board from "./Board";

describe("Board component", () => {
  test("renders a 10x10 grid, and checks for specific cells A5, E9", () => {
    render(<Board />);

    // Find all cells generated by 'createBoard'
    const cells = screen.getAllByRole("gridcell");

    //Check if there are 100 cells
    expect(cells).toHaveLength(100);

    // Check for specific cells
    expect(screen.getByTestId("A5")).toBeInTheDocument();
    expect(screen.getByTestId("E9")).toBeInTheDocument();
  });
});
